version: '3'

services:
  db:
    image: mongo:4.1.6
    hostname: mongo
    container_name: mongo_kaggle
    command: mongod --storageEngine wiredTiger --wiredTigerDirectoryForIndexes --directoryperdb --wiredTigerCollectionBlockCompressor zlib --wiredTigerCacheSizeGB 4 --wiredTigerIndexPrefixCompression true
    volumes:
      - /mnt/Data/MongoDB/Kaggle/microsoft-malware-prediction/db/:/data/db/
    networks:
      kaggle:
        aliases:
          - mongo
        ipv4_address: 172.16.0.2
  kaggle:
    image: kaggle
    build: .
    container_name: code_kaggle
    hostname: code
    environment:
      - PROJECT=microsoft-malware-prediction
      - IP_SERVER_MONGO=172.16.0.2
      - DB_NAME=kaggle_microsoft-malware-prediction
      - DIR_DATA_RAW=/data/raw/
      - SEED=1234
      - PERFORM_METHOD=EXTRACT_TRAIN
    volumes:
      -  ./code/:/microsoft-malware-prediction/
      -  ./results/:/data/results/
      -  /mnt/Data/Data_for_Challenges/Kaggle/microsoft-malware-prediction/raw/:/data/raw/
    networks:
      kaggle:
        aliases:
          - code
        ipv4_address: 172.16.0.3
    depends_on:
      - db



networks:
  kaggle:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
